lr: 0.001
rounds: 600
epochs: 50
batch_size: 64
dataset: "cifar10"
iid: false
alpha: 0.1 # Parameter for Dirichlet sampling
K: 20 # Total # of clients
PR: 1.0 # Participation rate
M: 0.15 # Percentage of byzantine clients
method: "FedAvg" # Options: Krum, AutoGM, TrimmedMean, TrustFedKD
attack: "Noise" # Options: Noise, ALIE, SF, Concentrate
device: "mps" # Options: cuda, cpu, mps
